---
- name: Install requirements
  become: true
  package:
    name: "{{ item }}"
    state: present
  with_items:
    - python-virtualenv
    - python-pynvim
    - nodejs
    - npm
  tags:
    - nvim
