---
- name: Install requirements
  become: true
  ansible.builtin.package:
    name: "{{ item }}"
    state: present
  with_items:
    - fontconfig
    - nodejs
    - npm
    - python-pynvim
    - python-setuptools
    - python-virtualenv
    - unzip
  tags:
    - nvim

- name: "Install packer from AUR"
  ansible.builtin.include_role:
    name: "jahrik.yay"
  vars:
    aur_packages:
      - nvim-packer-git
