---
- name: Install requirements
  become: true
  ansible.builtin.package:
    name: "{{ item }}"
    state: present
  with_items:
    - fd
    - fontconfig
    - nodejs
    - npm
    - python-pynvim
    - python-setuptools
    - python-virtualenv
    - ripgrep
    - unzip
