---
- name: Install requirements
  become: true
  community.general.pacman:
    update_cache: true
    name:
      - fd
      - fontconfig
      - neovim
      - ripgrep
      - tree-sitter-cli
      - unzip
    state: present
