---
- name: Install requirements (macOS)
  become: false
  community.general.homebrew:
    name:
      - fd
      - fontconfig
      - ripgrep
      - tree-sitter-cli
      - unzip
    state: present

- name: Install neovim (macOS)
  become: false
  community.general.homebrew:
    name: neovim
    state: present

- name: Install Nerd Font (macOS)
  become: false
  community.general.homebrew_cask:
    name: font-dejavu-sans-mono-nerd-font
    state: present
