---
- name: Install requirements
  become: true
  ansible.builtin.package:
    name:
      - curl
      - fd-find
      - fontconfig
      - git
      - ripgrep
      - unzip
    state: present
    update_cache: true
    cache_valid_time: 3600

- name: Install neovim
  become: true
  ansible.builtin.apt:
    name: neovim
    state: present
