---
- name: Update Repository cache
  become: true
  apt:
    update_cache: true
    cache_valid_time: 3600
  tags:
    - nvim

- name: Install requirements
  become: true
  package:
    name: "{{ item }}"
    state: present
  with_items:
    - python3-pynvim
    - python3-virtualenv
    - curl
    - git
    - dirmngr
    - nodejs
    - npm
  tags:
    - nvim

- name: Add neovim-ppa
  apt_repository:
    repo: 'ppa:neovim-ppa/stable'
    update_cache: true
