---
- name: Install requirements
  become: true
  ansible.builtin.package:
    name:
      - ca-certificates
      - curl
      - fd-find
      - fontconfig
      - git
      - gpg
      - python3-debian
      - ripgrep
      - unzip
    state: present
    update_cache: true
    cache_valid_time: 3600

- name: Check if neovim PPA keyring exists
  become: true
  ansible.builtin.stat:
    path: /usr/share/keyrings/neovim-ppa.gpg
  register: neovim_keyring

- name: Download neovim PPA signing key
  become: true
  vars:
    neovim_ppa_key_id: "0x9DBB0BE9366964F134855E2255F96FCF8231B6DD"
  ansible.builtin.get_url:
    url: "https://keyserver.ubuntu.com/pks/lookup?op=get&search={{ neovim_ppa_key_id }}"
    dest: /usr/share/keyrings/neovim-ppa.asc
    mode: "0644"
  when: not neovim_keyring.stat.exists

- name: Dearmor neovim PPA signing key
  become: true
  ansible.builtin.command: gpg --dearmor -o /usr/share/keyrings/neovim-ppa.gpg /usr/share/keyrings/neovim-ppa.asc
  args:
    creates: /usr/share/keyrings/neovim-ppa.gpg

- name: Add neovim PPA repository
  become: true
  ansible.builtin.deb822_repository:
    name: neovim-ppa
    types: deb
    uris: "https://ppa.launchpadcontent.net/neovim-ppa/unstable/ubuntu"
    suites: "{{ ansible_facts['distribution_release'] }}"
    components: main
    signed_by: /usr/share/keyrings/neovim-ppa.gpg
    state: present

- name: Install neovim
  become: true
  ansible.builtin.apt:
    name: neovim
    state: present
    update_cache: true

- name: Check if tree-sitter binary exists
  become: false
  ansible.builtin.stat:
    path: /usr/local/bin/tree-sitter
  register: tree_sitter_stat

- name: Download tree-sitter CLI
  become: true
  ansible.builtin.get_url:
    url: https://github.com/tree-sitter/tree-sitter/releases/latest/download/tree-sitter-linux-x64.gz
    dest: /tmp/tree-sitter.gz
    mode: "0644"
  when: not tree_sitter_stat.stat.exists

- name: Install tree-sitter CLI
  become: true
  ansible.builtin.shell: gunzip -c /tmp/tree-sitter.gz > /usr/local/bin/tree-sitter && chmod 755 /usr/local/bin/tree-sitter
  args:
    creates: /usr/local/bin/tree-sitter
