---
- name: Install requirements
  become: true
  package:
    name: "{{ item }}"
    state: present
    update_cache: true
    cache_valid_time: 3600
  with_items:
    - curl
    - dirmngr
    - fontconfig
    - git
    - python3-pynvim
    - python3-virtualenv
    - unzip
  tags:
    - nvim

- name: Add neovim-ppa
  apt_repository:
    repo: 'ppa:neovim-ppa/stable'
    update_cache: true
  tags:
    - nvim

- name: Install the gpg key for nodejs LTS
  apt_key:
    url: "https://deb.nodesource.com/gpgkey/nodesource.gpg.key"
    state: present
  tags:
    - nvim

- name: Install the nodejs 17 LTS repos
  apt_repository:
    repo: "deb https://deb.nodesource.com/node_17.x {{ ansible_distribution_release }} main"
    state: present
    update_cache: yes
  tags:
    - nvim

- name: Install nodejs
  apt:
    name: nodejs
    state: present
  tags:
    - nvim

- name: Gather package facts
  ansible.builtin.package_facts:
    manager: auto

# Ubuntu 20.04 comes with an old version of neovim
- name: Uninstall old versions of neovim if < 0.6
  apt:
    name: neovim
    state: absent
  when:
    - "'neovim' in ansible_facts.packages"
    - "ansible_facts.packages.neovim[0].version[:3] | float < 0.6"
  tags:
      - nvim
