---
##############
# Requirements
##############

- include_tasks: "{{ ansible_os_family | lower }}.yml"

- name: Create ~/.local/share/fonts directory
  become: false
  file:
    path: ~/.local/share/fonts
    state: directory
    recurse: true
  tags:
    - nvim

- name: Download Nerd Fonts (dejavu-sans-mono-nerfonts)
  become: false
  ansible.builtin.unarchive:
    src: https://github.com/ryanoasis/nerd-fonts/releases/download/v2.1.0/DejaVuSansMono.zip
    dest: ~/.local/share/fonts
    remote_src: yes
    creates: '~/.local/share/fonts/DejaVu Sans Mono Nerd Font Complete Mono.ttf'
  notify: fc-cache
  tags:
    - nvim

########
# Neovim
########

- name: Install neovim
  become: true
  package:
    name: neovim
    state: present
  tags:
    - nvim

- name: Install NPM packages
  become: true
  community.general.npm:
    name: neovim
    global: yes
    state: present

- name: Ensure /usr/local/share/nvim/ directory exists
  become: true
  file:
    mode: 0755
    path: /usr/local/share/nvim/
    state: directory

- name: Create python virtual env and install neovim module
  become: true
  pip:
    name: neovim
    virtualenv: /usr/local/share/nvim/python3
    virtualenv_python: python3

- name: create ~/.config/nvim directories
  become: false
  file:
    path: "~/.config/{{ item }}"
    state: directory
    mode: 0755
    recurse: true
  with_items:
    - "nvim"
    - "nvim/lua"
    - "nvim/after/plugin"
    # - "nvim/autoload"
    # - "nvim/init.d"
    # - "nvim/snips"
  tags:
    - nvim

########
# Packer
########

# Installed from AUR with yay instead.
# nvim-packer-git

# - name: create packer directories
#   become: false
#   file:
#     path: "~/.local/share/nvim/site/pack/packer/start/"
#     state: directory
#     mode: 0755
#     recurse: true
#   tags:
#     - nvim
# 
# - name: Install packer
#   become: false
#   get_url:
#     url: https://github.com/wbthomason/packer.nvim
#     dest: ~/.local/share/nvim/site/pack/packer/start/packer.nvim

#########
# Configs
#########

- name: generate nvim config files
  become: false
  template:
    src: "{{ item }}.j2"
    dest: "~/.config/nvim/{{ item }}"
  with_items:
    - init.lua
    - lua/remap.lua
    - lua/plugins.lua
    - after/plugin/telescope.lua
    - after/plugin/colors.lua
    - after/plugin/treesitter.lua
    - after/plugin/lsp.lua
  notify: "nvim packersync"
  tags:
    - nvim
