---
- name: Check for Steam Deck
  ansible.builtin.stat:
    path: /etc/steamos-release
  register: steamos_release

- name: Set is_steamdeck fact
  ansible.builtin.set_fact:
    is_steamdeck: "{{ steamos_release.stat.exists }}"

- name: Include OS specific tasks
  ansible.builtin.include_tasks: "{{ 'steamdeck' if is_steamdeck else ansible_os_family | lower }}.yml"

- name: Create ~/.local/share/fonts directory
  become: false
  ansible.builtin.file:
    path: ~/.local/share/fonts
    state: directory
    recurse: true
  when: ansible_os_family != 'Darwin'

- name: Download Nerd Fonts (dejavu-sans-mono-nerdfonts)
  become: false
  ansible.builtin.unarchive:
    src: https://github.com/ryanoasis/nerd-fonts/releases/download/v2.1.0/DejaVuSansMono.zip
    dest: ~/.local/share/fonts
    remote_src: true
    creates: '~/.local/share/fonts/DejaVu Sans Mono Nerd Font Complete Mono.ttf'
  notify: Fc-cache
  when: ansible_os_family != 'Darwin'

- name: Install neovim
  become: true
  ansible.builtin.package:
    name: neovim
    state: present
  when: ansible_os_family == 'Archlinux' and not is_steamdeck

- name: Create ~/.config/nvim directories
  become: false
  ansible.builtin.file:
    path: "~/.config/nvim/lua/{{ item }}"
    state: directory
    mode: "0755"
    recurse: true
  loop:
    - core
    - plugins

- name: Generate nvim config files
  become: false
  ansible.builtin.copy:
    src: "{{ item }}"
    dest: "~/.config/nvim/{{ item }}"
    mode: "0644"
  loop:
    - init.lua
    - lua/core/autocmds.lua
    - lua/core/keymaps.lua
    - lua/core/lazy.lua
    - lua/core/options.lua
    - lua/plugins/autopairs.lua
    - lua/plugins/blink.lua
    - lua/plugins/claude.lua
    - lua/plugins/colorscheme.lua
    - lua/plugins/conform.lua
    - lua/plugins/copilot.lua
    - lua/plugins/dadbod.lua
    - lua/plugins/dap.lua
    - lua/plugins/gitsigns.lua
    - lua/plugins/indent_line.lua
    - lua/plugins/lazydev.lua
    - lua/plugins/lazygit.lua
    - lua/plugins/lint.lua
    - lua/plugins/lsp.lua
    - lua/plugins/mini.lua
    - lua/plugins/neo-tree.lua
    - lua/plugins/neotest.lua
    - lua/plugins/telescope.lua
    - lua/plugins/todo_comments.lua
    - lua/plugins/treesitter.lua
    - lua/plugins/trouble.lua
    - lua/plugins/venv_selector.lua
    - lua/plugins/which_key.lua
