---
- name: Set is_steamdeck fact
  ansible.builtin.set_fact:
    is_steamdeck: "{{ ansible_distribution == 'SteamOS' }}"

- name: Include OS specific tasks
  ansible.builtin.include_tasks: "{{ 'steamdeck' if is_steamdeck else ansible_facts['os_family'] | lower }}.yml"

- name: Deploy nvim configuration
  become: false
  ansible.builtin.copy:
    src: files/
    dest: "~/.config/nvim/"
    mode: "0755"
