---
- include_tasks: archlinux.yml
  when: ansible_os_family == 'Archlinux'

- include_tasks: debian.yml
  when: ansible_os_family == 'Debian'

- name: Install neovim
  become: true
  package:
    name:
      - neovim
    state: latest
  tags:
    - nvim

- name: Install NPM packages
  become: true
  community.general.npm:
    name: "{{ item }}"
    path: /app/location
  with_items:
    - neovim
    - tree-sitter-cli

- name: Create python virtual env and install neovim module
  become: true
  pip:
    name: neovim
    virtualenv: /usr/local/share/nvim/python3
    virtualenv_python: python3

- name: create ~/.config/nvim directories
  become: false
  file:
    path: "~/.config/{{ item }}"
    state: directory
    mode: 0755
  with_items:
    - "nvim"
    - "nvim/init.d"
    - "nvim/lua.d"
    - "nvim/snips"
    - "nvim/autoload"
  tags:
    - nvim

- name: Install vim-plug
  become: false
  command: curl -fLo ~/.config/nvim/autoload/plug.vim https://raw.githubusercontent.com/junegunn/vim-plug/master/plug.vim
  args:
    creates: ~/.config/nvim/autoload/plug.vim

- name: generate nvim config files
  become: false
  template:
    src: "{{ item }}.j2"
    dest: "~/.config/nvim/{{ item }}"
  with_items:
    - init.vim
    - coc-settings.json
    - init.d/00.Init.vim
    - init.d/01.Keys.vim
    - init.d/02.Plug.vim
    - init.d/30.Coc.vim
    - init.d/31.BarBar.vim
    - init.d/31.BetterWhitespace.vim
    - init.d/31.FzfPreview.vim
    - init.d/31.GitMessenger.vim
    - init.d/31.LuaTree.vim
    - init.d/31.Startify.vim
    - init.d/31.TreeSitter.vim
    - init.d/31.VimTest.vim
    - init.d/90.FileTypes.vim
    - init.d/99.Theme.vim
    - lua.d/50.GalaxyLine.lua
    - lua.d/50.NvimTree.lua
    - snips/startify.snippets
  notify: "nvim plugin install"
  tags:
    - nvim

- name: Create ~/.local/share/fonts directory
  become: false
  file:
    path: ~/.local/share/fonts
    state: directory
    recurse: true
  tags:
    - nvim

- name: Download Nerd Fonts (dejavu-sands-mono-nerfonts)
  become: false
  ansible.builtin.unarchive:
    src: https://github.com/ryanoasis/nerd-fonts/releases/download/v2.1.0/DejaVuSansMono.zip
    dest: ~/.local/share/fonts
    remote_src: yes
    creates: '~/.local/share/fonts/DejaVu Sans Mono Nerd Font Complete Mono.ttf'
  notify: fc-cache
  tags:
    - nvim
