---
- name: Set is_steamdeck fact
  ansible.builtin.set_fact:
    is_steamdeck: "{{ ansible_distribution == 'SteamOS' }}"

- name: Uninstall neovim (macOS)
  become: false
  community.general.homebrew:
    name: neovim
    state: absent
  when: ansible_facts['os_family'] == 'Darwin'

- name: Remove neovim tarball binary (Steam Deck)
  become: false
  ansible.builtin.file:
    path: "{{ item }}"
    state: absent
  loop:
    - ~/.local/bin/nvim
    - ~/.local/lib/nvim
    - ~/.local/share/nvim
  when: is_steamdeck

- name: Uninstall neovim
  become: true
  ansible.builtin.package:
    name: neovim
    state: absent
  when: ansible_facts['os_family'] != 'Darwin' and not is_steamdeck

- name: Destroy ~/.config/nvim directory
  become: false
  ansible.builtin.file:
    path: ~/.config/nvim
    state: absent

- name: Destroy ~/.local/share/nvim directory
  become: false
  ansible.builtin.file:
    path: ~/.local/share/nvim
    state: absent
