---
- name: Uninstall neovim
  become: true
  ansible.builtin.package:
    name:
      - neovim
    state: absent
  tags:
    - nvim

- name: Destroy ~/.config/nvim directory
  become: false
  ansible.builtin.file:
    path: ~/.config/nvim
    state: absent
  tags:
    - nvim
