---
- name: nvim packersync
  become: false
  command: nvim --headless -c 'autocmd User PackerComplete quitall' -c 'PackerSync'

- name: fc-cache
  become: false
  command: fc-cache -f ~/.local/share/fonts/
