---
- name: Nvim packersync
  become: false
  ansible.builtin.command: timeout 60 nvim --headless -c 'autocmd User PackerComplete quitall' -c 'PackerSync'
  ignore_errors: true

- name: Fc-cache
  become: false
  ansible.builtin.command: fc-cache -f ~/.local/share/fonts/
  ignore_errors: true
