---
- name: Verify
  hosts: all
  gather_facts: false
  tasks:

  - name: Gather package facts
    ansible.builtin.package_facts:
      manager: auto

  - name: Assert neovim package installed
    ansible.builtin.assert:
      that: "'neovim' in ansible_facts.packages"

  - name: Stat ~/.config/nvim/init.lua file
    ansible.builtin.stat:
      path: ~/.config/nvim/init.lua
    register: init_lua

  - name: Assert ~/.config/nvim/init.lua exists
    become: false
    ansible.builtin.assert:
      that: init_lua.stat.exists

  - name: Stat ~/.config/nvim/lua/conf/plugins/lsp.lua file
    ansible.builtin.stat:
      path: ~/.config/nvim/lua/conf/plugins/lsp.lua
    register: lsp_lua

  - name: Assert ~/.config/nvim/lua/conf/plugins/lsp.lua exists
    ansible.builtin.assert:
      that: lsp_lua.stat.exists
