---
- name: Verify
  hosts: all
  gather_facts: false
  tasks:

  - name: Gather package facts
    ansible.builtin.package_facts:
      manager: auto

  - name: Assert neovim package installed
    assert:
      that: "'neovim' in ansible_facts.packages"

  - name: Stat ~/.config/nvim/init.lua file
    stat:
      path: ~/.config/nvim/init.lua
    register: init_lua

  - name: Assert ~/.config/nvim/init.lua exists
    become: false
    assert:
      that: init_lua.stat.exists

  - name: Check NPM packages
    become: true
    community.general.npm:
      name: neovim
      global: yes
    check_mode: true
    register: npm_packages

  - name: Assert NPM packages installed
    assert:
      that: not npm_packages.changed
